easy_admin:
    site_name: 'Develpup Admin'
    design:
        #brand_color: '#025939'
    entities:
        User:
            class: 'AppBundle\Entity\User'
            list:
                actions:
                    - { name: 'edit',   icon: 'edit',   label: '' }
                    - { name: 'delete', icon: 'trash', label: '' }
                fields:
                    - 'id'
                    - 'enabled'
                    - 'last_name'
                    - 'first_name'
                    - 'email'
                    - 'last_login'
            form:
                fields:
                    - 'first_name'
                    - 'last_name'
                    - { property: 'birth_date', type: 'birthday', type_options: { required: false, } }
                    - { property: 'gender', type: 'AppBundle\Form\Type\GenderType' }
                    - { property: 'email', icon: 'user' }
                    - { property: 'plainPassword', type: 'AppBundle\Form\Type\SetPasswordType' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { User: 'ROLE_USER', Admin: 'ROLE_ADMIN' } } }
            edit:
                fields:
                    - 'enabled'
                    - { property: 'plainPassword', type_options: { required: false} }
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'plainPassword', type_options: { required: true} }
                form_options: { validation_groups: ['Registration'] }
