fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    AppBundle\Entity\User
    from_email:
        address:     "%from_email_address%"
        sender_name: "%from_email_sender_name%"
    registration:
        form:
            type: AppBundle\Form\RegistrationFormType
