
services:

    # add more services, or override services
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value

    AppBundle\Security\UserManager:
        parent: fos_user.user_manager
